version: '3.8'

services:
  broker:
    image: eclipse-mosquitto:latest
    container_name: sentinel_mosquitto
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
    restart: always
  db:
    image: postgres:15-alpine
    container_name: sentinel_db
    environment:
      POSTGRES_USER: sentinel_user
      POSTGRES_PASSWORD: sentinel_password
      POSTGRES_DB: sentinel_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always
volumes:
  pgdata:
