[platformio]
extra_configs = private.ini
default_envs = esp32cam

[env:esp32cam]
platform = espressif32@6.6.0
board = esp32cam
framework = arduino
extra_scripts = pre:../generate_certs.py

; Serial Upload Configuration
upload_speed = 115200

; Serial Monitor Configuration
monitor_speed = 115200
monitor_dtr = 0
monitor_rts = 0
monitor_filters = 
    esp32_exception_decoder
    time
    colorize

build_flags =
    -Iinclude
    -I../../include
    -D BOARD_HAS_PSRAM
    -mfix-esp32-psram-cache-issue
    -D PIR_MODEL_AI_THINKER
    -D CORE_DEBUG_LEVEL=3
    -D WIFI_SSID=\"${private.wifi_ssid}\"
    -D WIFI_PASS=\"${private.wifi_pass}\"
    -D MQTT_BROKER_IP=\"${private.mqtt_broker}\"
