[platformio]
extra_configs = private.ini
default_envs = esp32cam

[env:esp32cam]
build_flags =
    -Iinclude
    -D BOARD_HAS_PSRAM
    -mfix-esp32-psram-cache-issue
    -D PIR_MODEL_AI_THINKER
    -D CORE_DEBUG_LEVEL=3
    -D WIFI_SSID=\"${private.wifi_ssid}\"
    -D WIFI_PASS=\"${private.wifi_pass}\"
    -D MQTT_BROKER_IP=\"${private.mqtt_broker}\"
