; ==============================================================================
; SentinelNode ESP32-CAM - PlatformIO Configuration (Production Grade)
# Pinned to Arduino Core 2.0.x, optimized for OV3660 stability & hardware PSRAM
; ==============================================================================

[platformio]
extra_configs = private.ini
default_envs = esp32cam

[env:esp32cam]
platform = espressif32@6.5.0
board = esp32cam
framework = arduino

; Serial Upload Configuration
upload_speed = 460800
upload_port = /dev/ttyUSB0

; Serial Monitor Configuration
monitor_speed = 115200
monitor_port = /dev/ttyUSB0
monitor_filters = 
    esp32_exception_decoder
    time
    colorize

; Partition Table: Min SPIFFS (gives two massive 1.9MB app/OTA partitions)
board_build.partitions = min_spiffs.csv

; Project Dependencies
lib_deps =
    knolleary/PubSubClient @ ^2.8

; Compiler Flags:
; 1. BOARD_HAS_PSRAM: Instructs the core to detect and mount external SPIRAM (4MB)
; 2. -mfix-esp32-psram-cache-issue: Essential hardware patch for early ESP32 revisions
; 3. CAMERA_MODEL_AI_THINKER: Pin definitions for standard ESP32-CAM boards
; 4. CORE_DEBUG_LEVEL: Output level of ESP-IDF / Arduino internal logs (3 = Info)
build_flags =
    -Iinclude
    -D BOARD_HAS_PSRAM
    -mfix-esp32-psram-cache-issue
    -D CAMERA_MODEL_AI_THINKER
    -D CORE_DEBUG_LEVEL=3
    -D WIFI_SSID=\"${private.wifi_ssid}\"
    -D WIFI_PASS=\"${private.wifi_pass}\"
    -D MQTT_BROKER_IP=\"${private.mqtt_broker}\"
